input_folder_path: "../data/car-rgb-ref/03/"
input_data_name: "03"
ref_image_ts_path: "../data/car-rgb-ref/03/image_ts.txt"
process_ts_start: -1
process_ts_end: -1
event_num_start: 2 
event_num_end: 10000000
width: 1281
height: 721
n_target: 2 # Default number of tracking target
data_format: 1 # 0: ts,c,r,p; 1: c,r,p,ts
ring_buffer_len: 10
dist_threshold: 10
publish_framerate: 40
contrast_threshold : 0.1
alpha: 50
m : 2 # Number of measurements
dt: 0.0001
n_state: 10 # Number of filter state


# Flags
use_gyro_flag: 0
save_video_flag: 0
save_image_flag: 0
save_track_flag: 0 
disp_covariance_flag: 0
compute_TTC_flag: 1
print_TTC_flag: 0
select_target_flag: 0 # Select by click or track pre-defined target
ref_image_ts_flag: 1


# Kalman filter
var_x: 10
var_y: 10   
var_vx: 500
var_vy: 500
var_lambda_1: 5
var_lambda_2: 5
var_theta: 0.5
var_q: 2
q_x: 200
q_y: 200
q_vx: 1000
q_vy: 1000
q_lambda_1: 1
q_lambda_2: 1
q_theta: 0.005
q_q: 0.01
position_x_init: [501, 579]
position_y_init: [250, 245]
lambda_init: 30

