input_folder_path: "../data/spin-dot/2-4/"
input_data_name: "spin-0-14000" 
ref_image_ts_path: ""
process_ts_start: -1
process_ts_end: -1
event_num_start:  3000000
event_num_end: 900000000000
width: 1281
height: 721
n_target: 1 # Default number of tracking target
data_format: 1 # 0: ts,c,r,p; 1: c,r,p,ts
ring_buffer_len: 10
dist_threshold: 60
publish_framerate: 40 
contrast_threshold : 0.1
alpha: 50
m : 2 # Number of measurements
dt: 0.0001
n_state: 10 # Number of filter state


# Flags
use_gyro_flag: 0
save_video_flag: 0
save_image_flag: 0
save_track_flag: 0
disp_covariance_flag: 0
compute_TTC_flag: 0
print_TTC_flag: 0
select_target_flag: 1 # Select by click or track pre-defined target
ref_image_ts_flag: 0


# Kalman filter
var_x: 100
var_y: 100   
var_vx: 10000
var_vy: 10000
var_lambda_1: 10
var_lambda_2: 10
var_theta: 0.5
var_q: 2
q_x: 1000
q_y: 1000
q_vx: 20000000
q_vy: 20000000
q_lambda_1: 0.01
q_lambda_2: 0.01
q_theta: 0.008
q_q: 0.01
position_x_init: [907]
position_y_init: [421]
lambda_init: 60